name: Cherry-pick

on: [push]

jobs:
  cherry-pick:
    env: 
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      PR_BRANCH: "feature/cherry-pick-123"
      INPUT_TARGETBRANCH: "feature/regression"
      PR_TITLE: "PR-123-regression-cherry-pick"
      PR_BODY: "Automated cherry-pick update from PR 123 https://github.com/VirtoCommerce/vc-platform/pull/2055"
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v1

    - uses: VirtoCommerce/vc-github-actions/setup-git-credentials-github@master
    
    - name: Cherry-pick
      run: |
          echo "-remote update"
          git remote update
          echo "-fetch --all"
          git fetch --all
          echo "-check-out"
          git checkout -b "${PR_BRANCH}" "origin/${INPUT_TARGETBRANCH}"
          echo "-cherry-pick"
          git cherry-pick "${GITHUB_SHA}"
          echo "-push"
          git push --set-upstream -u origin "${PR_BRANCH}"
          echo "-Create PR"
          hub pull-request -b "${INPUT_TARGETBRANCH}" -h "${PR_BRANCH}"-a "vc-ci" -m "${PR_TITLE}" -m "${PR_BODY}"
